### PR TITLE
Enabling more restrictive rubocop rules in ruby linting

### PR DESCRIPTION
**Pull request by FaragElsayed2**
- Enabling more restrictive rubocop rules in ruby linting
   -  `Style/FrozenStringLiteralComment`
   - `Metrics/MethodLength`
   - `RSpec/VariableName`
   - `Metrics/BlockNesting`

- Fixing #40

### CODE REVIEW

**Comment by atorkmabrains** [comment]
@proppy Please review.

**Comment by atorkmabrains** [comment]
@proppy This fixes: #40

**Comment by proppy** [comment]
@atorkmabrains can you remove `Draft` if it's ready for review?

**Comment by FaragElsayed2** [comment]
Hi @atorkmabrains  and @proppy 
- All rubocop rules have been enabled except the following rules:
   -  `GlobalVars`: I believe we couldn't enable it as we have used some variables passed from klayout run
   -  `UselessAssignment`: I think this rules will not be solvable as we use main runset as a wrapper for the other rule decks, so there are some variables are defined in main but used in the other runsets.

**Comment by proppy** [comment]
Great work!

Maybe we could enable those two rules, and add expection on a per line basis with the following comments at the end of line that are doing this?
```
# rubocop:disable Lint/UselessAssignment Style/GlobalVars
```

**Comment by atorkmabrains** [comment]
Thanks @proppy 

I was reviewing with Farag if we can do the suggestion above. But I believe it will be hard as we will have to add this comment all over the code. 

Appreciate if we could keep it as disabled.

**Comment by atorkmabrains** [comment]
@proppy We appreciate if you could approve this as we need to move all the tables one by one here.

**Comment by proppy** [comment]
Sure thanks for working on this /cc @mithro

**Pull request merged**
