### PR TITLE
Removing repeated log for klayout version

### PR DESCRIPTION
**Pull request by FaragElsayed2**
## Removing repeated log for klayout version

### CODE REVIEW

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Is this ticket done?

**Comment by FaragElsayed2** [comment]
@atorkmabrains Yes

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Comment by atorkmabrains** [comment]
@proppy Could you please merge this?

**Comment by proppy** [comment]
sorry I let that split, merging!

**Pull request merged**
